In [2]:
import pandas as pd
df = pd.read_csv("../data/diabetes_cleaned.csv")

In [2]:
df["Glucose"].mean()

np.float64(121.65625)

In [3]:
df.groupby("Outcome")["Glucose"].mean()

Outcome
0    110.682000
1    142.130597
Name: Glucose, dtype: float64

In [5]:
df.groupby("Outcome")["BMI"].mean()

Outcome
0    30.885600
1    35.383582
Name: BMI, dtype: float64

In [7]:
df.groupby("Outcome")["Glucose"].agg(["mean","min","max","count"])

               mean   min    max  count
Outcome
0        110.682000  44.0  197.0    500
1        142.130597  78.0  199.0    268

In [8]:
df.groupby("Outcome")[["Glucose" , "BMI" , "Age"]].mean()

            Glucose        BMI        Age
Outcome
0        110.682000  30.885600  31.190000
1        142.130597  35.383582  37.067164

In [9]:
df["Age_Group"] = pd.cut(df["Age"], bins=[20, 30, 40, 50, 100])
df.pivot_table(values="Glucose", index="Age_Group", columns="Outcome", aggfunc="mean")

Outcome             0           1
Age_Group
(20, 30]   108.051988  140.322222
(30, 40]   114.148148  140.539474
(40, 50]   108.000000  139.640625
(50, 100]  127.209302  153.789474

In [3]:
df.pivot_table(index = "Outcome", values = ["Glucose", "BMI"], aggfunc = ["mean", "min", "max", "count"])

              mean               min           max         count
               BMI     Glucose   BMI Glucose   BMI Glucose   BMI Glucose
Outcome
0        30.885600  110.682000  18.2    44.0  57.3   197.0   500     500
1        35.383582  142.130597  22.9    78.0  67.1   199.0   268     268

In [5]:
patients = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],})
results = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Test_Result": ["Positive", "Negative", "Positive", "Negative", "Positive"]})
merged = patients.merge(results , on = "Patient_ID")
merged

   Patient_ID     Name Test_Result
0           1    Alice    Positive
1           2      Bob    Negative
2           3  Charlie    Positive
3           4    David    Negative
4           5      Eva    Positive

In [6]:
patients = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],})
results = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Test_Result": ["Positive", "Negative", "Positive", "Negative", "Positive"]})
merged = patients.merge(results , on = "Patient_ID" , how = "left")
merged

   Patient_ID     Name Test_Result
0           1    Alice    Positive
1           2      Bob    Negative
2           3  Charlie    Positive
3           4    David    Negative
4           5      Eva    Positive

In [7]:
patients = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],})
results = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Test_Result": ["Positive", "Negative", "Positive", "Negative", "Positive"]})
merged = patients.merge(results , on = "Patient_ID" , how = "right")
merged

   Patient_ID     Name Test_Result
0           1    Alice    Positive
1           2      Bob    Negative
2           3  Charlie    Positive
3           4    David    Negative
4           5      Eva    Positive

In [8]:
patients = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],})
results = pd.DataFrame({
    "Patient_ID": [1, 2, 3, 4, 5],
    "Test_Result": ["Positive", "Negative", "Positive", "Negative", "Positive"]})
merged = patients.merge(results , on = "Patient_ID" , how = "outer")
merged

   Patient_ID     Name Test_Result
0           1    Alice    Positive
1           2      Bob    Negative
2           3  Charlie    Positive
3           4    David    Negative
4           5      Eva    Positive